sudo: false

language: java

jdk:
  - oraclejdk8

before_install:
  - unset _JAVA_OPTIONS

install:
  - ./mvnw --version

script:
  - ./mvnw clean install

before_cache:
  - git status
  - rm -rf $HOME/.m2/

cache:
  directories:
    - $HOME/.m2/
